const careerData = [
  { id: 0, Title: "1 mg", Link: "https://www.1mg.com/jobs" },
  { id: 1, Title: "314e Corporation", Link: "https://www.314e.com/company/job-openings/" },
  { id: 2, Title: "3i Infotech", Link: "https://www.3i-infotech.com/careers/" },
  { id: 3, Title: "[24]7.ai", Link: "https://www.247.ai/career-search" },
  { id: 4, Title: "Acaira", Link: "https://www.acaira.com/Career.aspx" },
  {
    id: 5,
    Title: "Accenture",
    Link: "https://www.accenture.com/in-en/careers",
  },
  {
    id: 6,
    Title: "Accolite software",
    Link: "https://www.accolite.com/careers",
  },
  {
    id: 7,
    Title: "Accord software",
    Link: "https://accord-global.com/careers.html",
  },
  { id: 8, Title: "Acko", Link: "https://acko.hirexp.com/" },
  { id: 9, Title: "Adobe", Link: "https://www.adobe.com/careers.html" },
  {
    id: 10,
    Title: "AGC Networks",
    Link: "https://www.agcnetworks.com/career/",
  },
  {
    id: 11,
    Title: "Agile Infoway",
    Link: "https://www.agileinfoways.com/careers/",
  },
  {
    id: 12,
    Title: "Agile Solutions",
    Link: "http://agilesolutions.com/careers-2/  ",
  },
  { id: 13, Title: "Agnikul Cosmos", Link: "https://agnikul.in/#/career" },
  { id: 14, Title: "Airbase", Link: "https://www.airbase.com/careers" },
  { id: 15, Title: "Airbnb", Link: "https://careers.airbnb.com/" },
  { id: 16, Title: "Airbus", Link: "https://www.airbus.com/careers.html" },
  { id: 17, Title: "AirGarage", Link: "https://airgara.ge/careers/" },
  { id: 18, Title: "Airtel x labs", Link: "https://careers.airtel.com/" },
  { id: 19, Title: "Ajio", Link: "https://www.ajio.com/ajio-careers" },
  { id: 20, Title: "Akamai", Link: "https://www.akamai.com/careers" },
  { id: 21, Title: "Alibaba Group", Link: "https://careers.alibaba.com" },
  { id: 22, Title: "Alphabet Inc", Link: "https://abc.xyz" },
  { id: 23, Title: "Alstom", Link: "https://www.alstom.com/careers" },
  { id: 24, Title: "Amadeus labs", Link: "https://jobs.amadeus.com/" },
  { id: 25, Title: "Amazon", Link: "https://www.amazon.jobs/en/" },
  { id: 26, Title: "Amdocs", Link: "https://asset.amdocs.com/careers/" },
  {
    id: 27,
    Title: "American express",
    Link: "https://www.americanexpress.com/en-us/careers/",
  },
  { id: 28, Title: "Amway", Link: "https://www.amway.in/about-amway/careers" },
  { id: 29, Title: "Anaxee", Link: "https://www.anaxee.com/career/" },
  {
    id: 30,
    Title: "Apex Technology",
    Link: "https://www.apextechnologies.info/job-vacancies.html",
  },
  { id: 31, Title: "Apna", Link: "https://www.instahyre.com/jobs-at-apna/" },
  {
    id: 32,
    Title: "App Dynamics",
    Link: "https://www.appdynamics.com/company/careers/india",
  },
  { id: 33, Title: "Appen", Link: "https://appen.com/jobs/" },
  { id: 34, Title: "AppInventiv", Link: "https://appinventiv.com/career/" },
  { id: 35, Title: "Apple", Link: "https://www.apple.com/jobs/in/" },
  { id: 36, Title: "Aptiv", Link: "https://jobs.aptiv.com/" },
  { id: 37, Title: "Arcesium", Link: "https://www.arcesium.com/careers.html" },
  {
    id: 38,
    Title: "Ardentisys",
    Link: "https://www.ardentisys.com/about-us/careers",
  },
  {
    id: 39,
    Title: "Arista Networks",
    Link: "https://www.arista.com/en/careers",
  },
  { id: 40, Title: "Ark Info", Link: "https://www.arkinfo.in/career" },
  { id: 41, Title: "Armaco", Link: "https://www.aramco.com" },
  {
    id: 42,
    Title: "Aryaka networks",
    Link: "https://www.linkedin.com/company/aryaka-networks/jobs?originalSubdomain=in",
  },
  {
    id: 43,
    Title: "Asteria Aerospace Ltd",
    Link: "https://asteria.co.in/careers/",
  },
  {
    id: 44,
    Title: "Athena Health",
    Link: "https://www.athenahealth.com/careers",
  },
  {
    id: 45,
    Title: "Ather Energy",
    Link: "https://www.atherenergy.com/careers",
  },
  { id: 46, Title: "Atlan", Link: "https://atlan.com/careers/" },
  {
    id: 47,
    Title: "Atlassian",
    Link: "https://www.atlassian.com/company/careers",
  },
  { id: 48, Title: "Atos", Link: "https://atos.net/en/careers" },
  {
    id: 49,
    Title: "Aujas",
    Link: "https://www.aujas.com/cybersecurity-careers",
  },
  {
    id: 50,
    Title: "Avail Finance",
    Link: "https://availfinance.in/opportunities/",
  },
  { id: 51, Title: "Avaya", Link: "https://careers.avaya.com/" },
  {
    id: 52,
    Title: "Bacancy Technology",
    Link: "https://www.bacancytechnology.com/careers",
  },
  { id: 53, Title: "Bain & Co", Link: "https://www.bain.com/careers/" },
  { id: 54, Title: "Bajaj", Link: "https://www.bajajgroup.org/careers" },
  {
    id: 55,
    Title: "BankBazar",
    Link: "https://www.bankbazaar.com/careers.html",
  },
  {
    id: 56,
    Title: "BARC India",
    Link: "https://www.barcindia.co.in/life-at-barc",
  },
  { id: 57, Title: "Barclays", Link: "https://home.barclays/careers/" },
  {
    id: 58,
    Title: "Bazaarvoice",
    Link: "https://www.bazaarvoice.com/company/careers/",
  },
  {
    id: 59,
    Title: "BearingPoint",
    Link: "https://www.bearingpoint.com/en/our-people/careers/",
  },
  {
    id: 60,
    Title: "Bellatrix Aerospace",
    Link: "http://www.bellatrixaerospace.com/",
  },
  {
    id: 61,
    Title: "Benchmark",
    Link: "https://benchmarkit.zohorecruit.com/jobs/Careers",
  },
  {
    id: 62,
    Title: "Berkshire Hathaway Inc",
    Link: "https://www.bhhc.com/careers/career-opportunities.aspx",
  },
  { id: 63, Title: "Better", Link: "https://better.com/about-us/careers" },
  { id: 64, Title: "BharatPe", Link: "https://bharatpe.com/career" },
  { id: 65, Title: "BigBasket", Link: "https://careers.bigbasket.com/" },
  { id: 66, Title: "Biocon", Link: "https://www.biocon.com/careers/" },
  {
    id: 67,
    Title: "Bitrix Infotech",
    Link: "https://bitrixinfotech.com/career",
  },
  { id: 68, Title: "BlackBuck", Link: "https://www.blackbuck.com/careers.php" },
  {
    id: 69,
    Title: "Blackhawk",
    Link: "https://blackhawknetwork.com/company/careers",
  },
  { id: 70, Title: "Blackrock", Link: "https://careers.blackrock.com/" },
  {
    id: 71,
    Title: "Blizzard Entertainment",
    Link: "https://careers.blizzard.com/global/en",
  },
  {
    id: 72,
    Title: "Bloomberg L.P.",
    Link: "https://careers.bloomberg.com/job/search",
  },
  { id: 73, Title: "BlueJeans", Link: "https://www.bluejeans.com/careers" },
  {
    id: 74,
    Title: "Bluestacks",
    Link: "https://www.bluestacks.com/work-at-bluestacks.html",
  },
  {
    id: 75,
    Title: "BMC Software",
    Link: "https://www.bmc.com/careers/careers.html",
  },
  { id: 76, Title: "BNY Mellon", Link: "https://jobs.bnymellon.com/" },
  { id: 77, Title: "Boeing", Link: "https://jobs.boeing.com/" },
  { id: 78, Title: "Booking.com", Link: "https://jobs.booking.com/careers" },
  { id: 79, Title: "Bosch", Link: "https://www.bosch.in/careers/" },
  {
    id: 80,
    Title: "Bottemline Technologies",
    Link: "https://www.bottomline.com/apac/about/careers",
  },
  {
    id: 81,
    Title: "Bounce",
    Link: "https://careers-bounce.peoplestrong.com/portal/job/joblist",
  },
  { id: 82, Title: "BPL India", Link: "https://www.bplindia.in/careers.html" },
  {
    id: 83,
    Title: "Brahmastra Aerospace",
    Link: "https://www.brahmastraspace.org/career",
  },
  {
    id: 84,
    Title: "Brooklinen",
    Link: "https://www.brooklinen.com/pages/careers",
  },
  {
    id: 85,
    Title: "BrowserStack",
    Link: "https://www.browserstack.com/careers",
  },
  { id: 86, Title: "BT Global Services", Link: "https://www.bt.com/careers" },
  { id: 87, Title: "BukuWarung", Link: "https://www.notion.so/" },
  {
    id: 88,
    Title: "Byju's",
    Link: "https://byjus.com/careers/all-openings/job-category/tech/",
  },
  { id: 89, Title: "BYJU’S", Link: "https://byjus.com/careers-at-byjus/" },
  { id: 90, Title: "ByteDance", Link: "https://jobs.bytedance.com/en" },
  { id: 91, Title: "Byteridge", Link: "https://byteridge.com/career.html" },
  {
    id: 92,
    Title: "Cadence",
    Link: "https://www.cadence.com/en_US/home/company/careers.html",
  },
  { id: 93, Title: "Cameo", Link: "https://careers.cameo.com" },
  {
    id: 94,
    Title: "Capgemini",
    Link: "https://www.capgemini.com/in-en/careers/",
  },
  {
    id: 95,
    Title: "Capillary",
    Link: "https://www.capillarytech.com/about-us/careers/",
  },
  { id: 96, Title: "Capita", Link: "https://www.capita.com/careers" },
  {
    id: 97,
    Title: "Capital Numbers",
    Link: "https://www.capitalnumbers.com/careers.php",
  },
  { id: 98, Title: "CarDekho", Link: "https://careers.cardekho.com/" },
  { id: 99, Title: "CarWale", Link: "https://www.carwale.com/career/" },
  { id: 100, Title: "CasaOne", Link: "https://casaone.skillate.com/" },
  { id: 101, Title: "CashFree", Link: "https://www.cashfree.com/careers" },
  { id: 102, Title: "Celigo", Link: "https://www.celigo.com/company/careers/" },
  { id: 103, Title: "Cerner", Link: "https://careers.cerner.com/" },
  { id: 104, Title: "Cerner", Link: "https://careers.cerner.com/" },
  { id: 105, Title: "CGI Group", Link: "https://www.cgi.com/en/careers" },
  { id: 106, Title: "Chargebee", Link: "https://careers.chargebee.com/jobs/" },
  { id: 107, Title: "Chime", Link: "https://www.chime.com/careers/" },
  { id: 108, Title: "Chronus", Link: "https://chronus.com/about-us/careers" },
  {
    id: 109,
    Title: "Ciesto Solutions",
    Link: "https://ciestosolutions.com/career-opportunities/",
  },
  { id: 110, Title: "Cimpress", Link: "https://cimpress.com/careers/" },
  { id: 111, Title: "Cisco", Link: "https://jobs.cisco.com/" },
  { id: 112, Title: "Citicorp", Link: "https://careers.citigroup.com/" },
  { id: 113, Title: "Citrix", Link: "https://jobs.citrix.com/" },
  {
    id: 114,
    Title: "Clarion Technologies",
    Link: "https://www.clariontech.com/careers",
  },
  {
    id: 115,
    Title: "Classic Informatics",
    Link: "https://www.classicinformatics.com/careers/",
  },
  {
    id: 116,
    Title: "Clavis Technologies",
    Link: "https://www.clavistechnologies.com/careers/",
  },
  { id: 117, Title: "ClearTax", Link: "https://cleartax.in/s/careers" },
  { id: 118, Title: "ClearTrip", Link: "https://careers.cleartrip.com/" },
  { id: 119, Title: "Cloudera", Link: "https://www.cloudera.com/careers.html" },
  {
    id: 120,
    Title: "Code Nation",
    Link: "http://codenation.co.in/hiringphilosophy.html",
  },
  {
    id: 121,
    Title: "Codenation innovation labs",
    Link: "http://codenation.co.in/hiringprocess.html",
  },
  {
    id: 122,
    Title: "CodingNinjas",
    Link: "https://www.linkedin.com/jobs/coding-ninjas-jobs/?originalSubdomain=in",
  },
  { id: 123, Title: "Cognizant", Link: "https://careers.cognizant.com/in/en" },
  { id: 124, Title: "Cognologix", Link: "https://cognologix.com/" },
  {
    id: 125,
    Title: "Cohesity",
    Link: "https://www.cohesity.com/company/careers/",
  },
  { id: 126, Title: "CoinDCX", Link: "https://careers.coindcx.com/" },
  {
    id: 127,
    Title: "Coinswitch kuber",
    Link: "https://recruiterflow.com/coinswitch/jobs",
  },
  { id: 128, Title: "Collabera", Link: "https://www.collabera.com/job-apply/" },
  { id: 129, Title: "Commvault", Link: "https://careers.commvault.com/" },
  {
    id: 130,
    Title: "Comsoft",
    Link: "https://www.comsoft.com.sg/EN/html/careers.htm",
  },
  { id: 131, Title: "Confluent", Link: "https://www.confluent.io/careers/" },
  {
    id: 132,
    Title: "Continental",
    Link: "https://www.continental.com/en/career/",
  },
  { id: 133, Title: "Copucom", Link: "https://www.compucom.com/careers/" },
  { id: 134, Title: "COSGrid", Link: "https://www.cosgrid.com/careers" },
  {
    id: 135,
    Title: "Cradlepoint",
    Link: "https://cradlepoint.com/about-us/careers/job-listings/",
  },
  { id: 136, Title: "CRED", Link: "https://careers.cred.club/" },
  {
    id: 137,
    Title: "Credit Suisse",
    Link: "https://www.credit-suisse.com/careers/en/apply.html",
  },
  {
    id: 138,
    Title: "Crestron",
    Link: "https://www.crestron.com/About/careers-jobs-employment-opportunities",
  },
  { id: 139, Title: "Crio.Do", Link: "https://www.crio.do/recruit/" },
  {
    id: 140,
    Title: "Crowdstrike",
    Link: "https://www.crowdstrike.com/careers/",
  },
  {
    id: 141,
    Title: "CSS Corp",
    Link: "https://www.csscorp.com/company/careers/",
  },
  {
    id: 142,
    Title: "CueMath",
    Link: "https://www.cuemath.com/work-from-home/",
  },
  { id: 143, Title: "Cure.Fit", Link: "https://www.cure.fit/careers" },
  { id: 144, Title: "Curology", Link: "https://curology.com/careers/" },
  { id: 145, Title: "Cvent", Link: "https://www.cvent.com/en/careers" },
  {
    id: 146,
    Title: "Cybage",
    Link: "https://www.cybage.com/careers/current-openings",
  },
  {
    id: 147,
    Title: "Cygnet",
    Link: "https://www.cygnet-infotech.com/job-opportunities",
  },
  {
    id: 148,
    Title: "Daffodil Software",
    Link: "https://www.daffodilsw.com/career",
  },
  { id: 149, Title: "DailyHunt", Link: "https://careers.dailyhunt.com/#!/" },
  {
    id: 150,
    Title: "Databricks",
    Link: "https://databricks.com/company/careers",
  },
  { id: 151, Title: "Datadog", Link: "https://www.datadoghq.com/careers/" },
  {
    id: 152,
    Title: "Datamatics",
    Link: "http://careers.datamatics.com/dm_career/client/index.aspx",
  },
  { id: 153, Title: "Dave", Link: "https://dave.com/careers" },
  { id: 154, Title: "DE Shaw", Link: "https://www.deshawindia.com/careers" },
  {
    id: 155,
    Title: "DealShare",
    Link: "https://www.dealshare.in/careers#home",
  },
  { id: 156, Title: "Delhivery", Link: "https://www.delhivery.com/careers/" },
  {
    id: 157,
    Title: "Dell EMC",
    Link: "https://www.dell.com/learn/in/en/incorp1/viewall/careers",
  },
  { id: 158, Title: "Dell", Link: "https://jobs.dell.com/" },
  {
    id: 159,
    Title: "Delta Air Lines",
    Link: "https://delta.avature.net/careers",
  },
  { id: 160, Title: "Deolitte", Link: "https://jobs2.deloitte.com/ui/en" },
  { id: 161, Title: "Design.codes", Link: "https://designs.codes/career/" },
  { id: 162, Title: "Deutsche Bank", Link: "https://careers.db.com/" },
  {
    id: 163,
    Title: "Dhruva Space",
    Link: "https://angel.co/company/dhruvaspace",
  },
  { id: 164, Title: "Dialpad", Link: "https://www.dialpad.com/careers/" },
  {
    id: 165,
    Title: "Diebold",
    Link: "https://www.dieboldnixdorf.com/en-us/careers",
  },
  {
    id: 166,
    Title: "Dimension Data",
    Link: "https://www.dimensiondata.com/en-gb/careers",
  },
  { id: 167, Title: "Directi", Link: "https://careers.directi.com/" },
  { id: 168, Title: "Discord", Link: "https://discord.com/jobs" },
  {
    id: 169,
    Title: "Discovery inc",
    Link: "https://jobs.discovery.com/careers-home/",
  },
  {
    id: 170,
    Title: "Disney",
    Link: "https://jobs.disneycareers.com/location/india-jobs/391-28648/1269750/2",
  },
  { id: 171, Title: "Dispatch", Link: "https://www.naukri.com/dispatch-jobs" },
  { id: 172, Title: "Divvy Homes", Link: "https://jobs.lever.co/divvyhomes" },
  {
    id: 173,
    Title: "DP World",
    Link: "https://ehpv.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/,requisitions",
  },
  { id: 174, Title: "DRDO", Link: "https://www.drdo.gov.in/careers" },
  { id: 175, Title: "Dream11", Link: "https://www.dreamsports.group/careers" },
  { id: 176, Title: "DropBox", Link: "https://www.datadoghq.com/careers/" },
  { id: 177, Title: "Druva", Link: "https://www.druva.com/about/careers/" },
  {
    id: 178,
    Title: "Duck Creek Technologies",
    Link: "https://www.duckcreek.com/careers/",
  },
  {
    id: 179,
    Title: "Dukaan",
    Link: "https://angel.co/company/dukaan-app/jobs",
  },
  { id: 180, Title: "Dunzo", Link: "https://www.dunzo.com/careers" },
  { id: 181, Title: "EA Games", Link: "https://www.ea.com/careers" },
  { id: 182, Title: "eBay", Link: "https://careers.ebayinc.com/" },
  {
    id: 183,
    Title: "Ecolousys Technologies",
    Link: "https://www.naukri.com/ecclousys-technologies-jobs-careers-5221778",
  },
  {
    id: 184,
    Title: "Ecotech",
    Link: "https://www.ecotech.com/careers/career-opportunities/",
  },
  { id: 185, Title: "Enfussion", Link: "https://enfusion.com/careers/" },
  {
    id: 186,
    Title: "Envestnet Yodlee",
    Link: "https://www.yodlee.com/company/careers",
  },
  { id: 187, Title: "Ericsson", Link: "https://www.ericsson.com/en/careers" },
  { id: 188, Title: "Eurofins", Link: "https://careers.eurofins.com/in/" },
  {
    id: 189,
    Title: "Exceptionaire",
    Link: "https://www.exceptionaire.com/careers/",
  },
  { id: 190, Title: "EXL Healthcare", Link: "https://exlservice.com/careers" },
  { id: 191, Title: "Expedia", Link: "https://lifeatexpediagroup.com/jobs/" },
  { id: 192, Title: "Experian", Link: "https://www.experian.in/careers" },
  { id: 193, Title: "EY", Link: "https://careers.ey.com/" },
  { id: 194, Title: "EyeROV", Link: "https://www.eyerov.com/careers/" },
  { id: 195, Title: "Facebook", Link: "https://www.facebook.com/careers/" },
  { id: 196, Title: "FamPay", Link: "https://fampay.in/careers" },
  {
    id: 197,
    Title: "Fidelity Investments",
    Link: "https://india.fidelity.com/careers/",
  },
  {
    id: 198,
    Title: "Fidelity investments",
    Link: "https://jobs.fidelity.com/",
  },
  { id: 199, Title: "Fingent", Link: "https://www.fingent.com/careers/" },
  {
    id: 200,
    Title: "FireEye inc",
    Link: "https://www.fireeye.com/company/jobs.html",
  },
  {
    id: 201,
    Title: "Fischer Jordan",
    Link: "https://fischerjordan.com/careers/",
  },
  { id: 202, Title: "Fiserv", Link: "https://www.careers.fiserv.com" },
  {
    id: 203,
    Title: "Flatworld Solutions",
    Link: "https://www.flatworldsolutions.com/careers/forms/apply.php",
  },
  {
    id: 204,
    Title: "Flexport",
    Link: "https://www.flexport.com/careers/jobs/",
  },
  { id: 205, Title: "Flipkart", Link: "https://www.flipkartcareers.com/" },
  { id: 206, Title: "Flock", Link: "https://careers.flock.com/" },
  {
    id: 207,
    Title: "FlyFin",
    Link: "https://www.linkedin.com/company/flyfin-ai/jobs/",
  },
  { id: 208, Title: "Flytxt", Link: "https://www.flytxt.com/job/" },
  { id: 209, Title: "Fractal", Link: "https://fractal.ai/job-openings/" },
  { id: 210, Title: "Frappe Technologies", Link: "https://frappe.io/careers" },
  { id: 211, Title: "FreeCharge", Link: "https://careers.freecharge.in/" },
  {
    id: 212,
    Title: "Freshworks",
    Link: "https://www.freshworks.com/company/careers/",
  },
  {
    id: 213,
    Title: "Frontrow",
    Link: "https://www.gofrontrow.com/about/careers/",
  },
  {
    id: 214,
    Title: "Frugal Testing",
    Link: "https://frugaltesting.com/careers",
  },
  { id: 215, Title: "Full Story", Link: "https://www.fullstory.com/careers" },
  { id: 216, Title: "Furlenco", Link: "https://jobs.furlenco.com/" },
  { id: 217, Title: "fyle", Link: "https://www.fylehq.com/company/team/join" },
  { id: 218, Title: "Fynd", Link: "https://fynd.careers/" },
  { id: 219, Title: "Gartner", Link: "https://jobs.gartner.com/" },
  {
    id: 220,
    Title: "Garuda Aerospace private Ltd",
    Link: "https://www.garudaaerospace.com/",
  },
  {
    id: 221,
    Title: "GE Healthcare",
    Link: "https://jobs.gecareers.com/healthcare/global/en",
  },
  { id: 222, Title: "GE", Link: "https://www.ge.com/in/careers/opportunities" },
  {
    id: 223,
    Title: "GeeksForGeeks",
    Link: "https://www.geeksforgeeks.org/careers/?",
  },
  { id: 224, Title: "Ghost", Link: "https://careers.ghost.org/" },
  { id: 225, Title: "Github", Link: "https://github.com/about/careers" },
  { id: 226, Title: "Gitlab", Link: "https://about.gitlab.com/jobs/" },
  {
    id: 227,
    Title: "Global Logic",
    Link: "https://www.globallogic.com/in/careers/",
  },
  { id: 228, Title: "Global Space", Link: "https://globalspace.in/career.php" },
  { id: 229, Title: "Glu", Link: "https://www.glu.com/working-at-glu/" },
  { id: 230, Title: "Gobussoft", Link: "https://globussoft.com/vacancies/" },
  { id: 231, Title: "GoDaddy", Link: "https://careers.godaddy.com/" },
  { id: 232, Title: "GoDigit", Link: "https://www.godigit.com/" },
  {
    id: 233,
    Title: "Godrej Aerospace",
    Link: "https://www.godrej.com/godrejandboyce/gnb-careers",
  },
  { id: 234, Title: "Goibibo", Link: "https://www.goibibo.com/careers/" },
  { id: 235, Title: "Gojek", Link: "https://career.gojek.com/" },
  {
    id: 236,
    Title: "Goldman Sachs",
    Link: "https://www.goldmansachs.com/careers/",
  },
  { id: 237, Title: "Google", Link: "https://careers.google.com/" },
  { id: 238, Title: "Grab", Link: "https://grab.careers/" },
  {
    id: 239,
    Title: "Graviton",
    Link: "https://www.gravitontrading.com/careers.html",
  },
  {
    id: 240,
    Title: "GreyOrange",
    Link: "https://www.greyorange.com/about/careers/",
  },
  { id: 241, Title: "Greysoft", Link: "http://greysoft.co/careers" },
  { id: 242, Title: "Grofers", Link: "https://grofers.com/careers/" },
  { id: 243, Title: "Groupon", Link: "https://www.grouponcareers.com/" },
  { id: 244, Title: "Groww", Link: "https://groww.skillate.com/" },
  {
    id: 245,
    Title: "Guild Education",
    Link: "https://careers.guildeducation.com",
  },
  {
    id: 246,
    Title: "Hackerearth",
    Link: "https://www.hackerearth.com/careers/",
  },
  { id: 247, Title: "HackerRank", Link: "https://www.hackerrank.com/careers" },
  { id: 248, Title: "Harness", Link: "https://harness.io/careers/" },
  { id: 249, Title: "Hashedin", Link: "https://hashedin.com/careers/" },
  { id: 250, Title: "HBO", Link: "https://warnermediacareers.com/hbo-jobs" },
  {
    id: 251,
    Title: "HealthAsyst",
    Link: "https://www.healthasyst.com/careers/",
  },
  {
    id: 252,
    Title: "Healthify me",
    Link: "https://www.healthifyme.com/careers/",
  },
  { id: 253, Title: "HERE", Link: "https://www.here.com/careers" },
  { id: 254, Title: "Hewlett-Packard", Link: "https://jobs.hp.com/en-us/" },
  { id: 255, Title: "HIE HQ", Link: "https://hiehq.com/career" },
  { id: 256, Title: "Hike messenger", Link: "https://www.hike.in/workathike/" },
  {
    id: 257,
    Title: "Hiring Plug",
    Link: "https://www.hiringplug.com/careers.php",
  },
  { id: 258, Title: "Hitachi", Link: "https://careers.hitachi.com" },
  { id: 259, Title: "Honeywell", Link: "https://tech.hotstar.com/" },
  { id: 260, Title: "Hotstar", Link: "https://tech.hotstar.com/" },
  { id: 261, Title: "HP", Link: "https://jobs.hp.com/" },
  {
    id: 262,
    Title: "HRDevi Talent Acquistion",
    Link: "http://www.hrdevi.co.in",
  },
  { id: 263, Title: "HSBC", Link: "https://www.hsbc.com/careers" },
  { id: 264, Title: "HubSpot", Link: "https://www.hubspot.com/careers" },
  {
    id: 265,
    Title: "Hyperlink InfoSystem",
    Link: "https://www.hyperlinkinfosystem.com/career.html",
  },
  {
    id: 266,
    Title: "Hyundai",
    Link: "https://www.hyundai.com/in/en/hyundai-story/career/overview.html",
  },
  { id: 267, Title: "Iasys", Link: "https://www.iasys.co.in/career.php" },
  { id: 268, Title: "IBM", Link: "https://www.ibm.com/in-en/employment/" },
  { id: 269, Title: "IdeaForge", Link: "https://www.ideaforge.co.in/career/" },
  {
    id: 270,
    Title: "Igneous Infotech",
    Link: "http://ingenious-infotech.com/#career",
  },
  { id: 271, Title: "IHS Markit", Link: "https://careers.ihsmarkit.com/" },
  {
    id: 272,
    Title: "Impact Analytics",
    Link: "https://www.impactanalytics.co/join-us/",
  },
  { id: 273, Title: "InApp", Link: "https://inapp.com/careers/jobs-at-inapp/" },
  { id: 274, Title: "Incedoic", Link: "https://www.incedoinc.com/careers/" },
  { id: 275, Title: "Indeed", Link: "https://in.indeed.com/cmp/Indeed" },
  { id: 276, Title: "India Mart", Link: "https://careers.indiamart.com/" },
  { id: 277, Title: "Infilon", Link: "https://www.infilon.com/career/" },
  { id: 278, Title: "Info Edge", Link: "https://careers.infoedge.com/" },
  { id: 279, Title: "Infonaya", Link: "https://www.infonaya.com/Career.aspx" },
  { id: 280, Title: "Infor", Link: "https://www.infor.com/about/careers" },
  {
    id: 281,
    Title: "Informatica",
    Link: "https://informatica.gr8people.com/jobs",
  },
  {
    id: 282,
    Title: "Informatics",
    Link: "https://www.informaticsglobal.com/careers/",
  },
  { id: 283, Title: "Infosys", Link: "https://www.infosys.com/careers.html" },
  { id: 284, Title: "Inmobi", Link: "https://www.inmobi.com/company/careers/" },
  { id: 285, Title: "Innovaccer", Link: "https://innovaccer.com/careers/" },
  {
    id: 286,
    Title: "Intel",
    Link: "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
  },
  {
    id: 287,
    Title: "Intel",
    Link: "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
  },
  { id: 288, Title: "Intellika", Link: "https://www.intellika.in/careers/" },
  { id: 289, Title: "Intuit", Link: "https://www.intuit.com/careers/" },
  { id: 290, Title: "InVision", Link: "https://www.invisionapp.com/careers" },
  {
    id: 291,
    Title: "ION Energy",
    Link: "https://apply.workable.com/ionenergy/?lng=en",
  },
  { id: 292, Title: "IP Infusion", Link: "https://www.ipinfusion.com/career/" },
  {
    id: 293,
    Title: "iQuanti",
    Link: "https://www.iquanti.com/contact-us/careers/",
  },
  { id: 294, Title: "IQVIA", Link: "https://jobs.iqvia.com/" },
  {
    id: 295,
    Title: "Iron Mountain",
    Link: "https://www.ironmountain.com/in/about-us/careers",
  },
  { id: 296, Title: "Ishir", Link: "https://www.ishir.com/career.htm" },
  { id: 297, Title: "ISRO", Link: "https://www.isro.gov.in/careers" },
  {
    id: 298,
    Title: "Itransition",
    Link: "https://www.itransition.com/company/career",
  },
  { id: 299, Title: "Ixigo", Link: "https://www.ixigo.com/about/careers/" },
  { id: 300, Title: "Jaguar", Link: "https://www.jaguarlandrovercareers.com/" },
  { id: 301, Title: "Jeavio", Link: "https://www.jeavio.com/careers" },
  { id: 302, Title: "Jio", Link: "https://careers.jio.com/" },
  {
    id: 303,
    Title: "JP Morgan",
    Link: "https://careers.jpmorgan.com/IN/en/home",
  },
  { id: 304, Title: "Jumbotail", Link: "https://jumbotail.com/careers/" },
  {
    id: 305,
    Title: "Junglee Games",
    Link: "https://www.jungleegames.com/grow.php",
  },
  {
    id: 306,
    Title: "Juniper Networks",
    Link: "https://www.juniper.net/us/en/company/careers/",
  },
  { id: 307, Title: "Jupiter money", Link: "https://jobs.lever.co/jupiter" },
  { id: 308, Title: "Juspay", Link: "https://www.juspay.in/careers" },
  { id: 309, Title: "Kaleyra", Link: "https://www.kaleyra.com/careers/" },
  { id: 310, Title: "Kantar", Link: "https://www.kantar.com/careers" },
  {
    id: 311,
    Title: "Kesari bharat",
    Link: "https://www.linkedin.com/in/deepak-sharda-6594561b1/",
  },
  { id: 312, Title: "Keyvalue", Link: "https://keyvalue.systems/" },
  { id: 313, Title: "Khatabook", Link: "https://khatabook.com/hiring" },
  { id: 314, Title: "Khoros", Link: "https://khoros.com/about/careers" },
  { id: 315, Title: "Kickstarter", Link: "https://jobs.kickstarter.com/" },
  { id: 316, Title: "KLA Tencor", Link: "https://www.kla-tencor.com/careers" },
  { id: 317, Title: "Koch", Link: "https://jobs.kochcareers.com/" },
  { id: 318, Title: "KPN", Link: "http://www.kpn-corp.com/?page_id=201" },
  {
    id: 319,
    Title: "Land rover",
    Link: "https://www.jaguarlandrovercareers.com/",
  },
  {
    id: 320,
    Title: "Leap Finance",
    Link: "https://leapfinance.freshteam.com/jobs",
  },
  { id: 321, Title: "Lenovo", Link: "https://lenovocareers.com/" },
  { id: 322, Title: "Lenskart", Link: "https://hiring.lenskart.com/" },
  { id: 323, Title: "Licious", Link: "https://www.careers.in/" },
  { id: 324, Title: "LinkedIn", Link: "https://careers.linkedin.com/" },
  { id: 325, Title: "Livspace", Link: "https://www.livspace.com/in/careers" },
  {
    id: 326,
    Title: "Lockheed Martin",
    Link: "https://www.lockheedmartin.com/en-ca/careers.html",
  },
  {
    id: 327,
    Title: "Logica",
    Link: "https://www.naukri.com/logica-pvt-ltd-jobs-careers-333271",
  },
  { id: 328, Title: "LogicFruit", Link: "https://www.logic-fruit.com/" },
  {
    id: 329,
    Title: "Logicmonitor",
    Link: "https://www.logicmonitor.com/careers",
  },
  {
    id: 330,
    Title: "Lowe's companies, inc",
    Link: "https://corporate.lowes.com/careers/search-apply",
  },
  {
    id: 331,
    Title: "LTI",
    Link: "https://careers.lntinfotech.com/search/careers.lnt…com?q=&sortColumn=referencedate&sortDirection=asc",
  },
  {
    id: 332,
    Title: "Lululemon",
    Link: "https://careers.lululemon.com/en_US/careers",
  },
  {
    id: 333,
    Title: "Magazine3",
    Link: "https://www.naukri.com/magazine3-jobs-careers-2374534",
  },
  {
    id: 334,
    Title: "Magicpin",
    Link: "https://magicpin.darwinbox.in/ms/candidate/careers",
  },
  { id: 335, Title: "Mahindra", Link: "https://careers.techmahindra.com" },
  { id: 336, Title: "MakeMyTrip", Link: "https://careers.makemytrip.com/" },
  {
    id: 337,
    Title: "Mantech International",
    Link: "https://www.mantech.com/careers",
  },
  { id: 338, Title: "Maq", Link: "https://maqsoftware.com/careers" },
  {
    id: 339,
    Title: "Master Card",
    Link: "https://www.mastercard.us/en-us/vision/who-we-are/careers.html",
  },
  { id: 340, Title: "Master Class", Link: "https://careers.masterclass.com" },
  {
    id: 341,
    Title: "Mathworks",
    Link: "https://in.mathworks.com/company/jobs/opportunities.html",
  },
  {
    id: 342,
    Title: "Maven Workforce",
    Link: "https://www.mavenworkforce.com/jobs",
  },
  { id: 343, Title: "McAfee", Link: "https://careers.mcafee.com/search-jobs" },
  { id: 344, Title: "Media.net", Link: "https://careers.media.net/" },
  { id: 345, Title: "Media.net", Link: "https://careers.media.net/" },
  { id: 346, Title: "Meesho", Link: "https://careers.meesho.com/" },
  { id: 347, Title: "Meesho", Link: "https://careers.meesho.com/" },
  { id: 348, Title: "Memory", Link: "https://memory.ai/jobs" },
  { id: 349, Title: "Micron", Link: "https://micron.eightfold.ai/careers" },
  {
    id: 350,
    Title: "Microsoft",
    Link: "https://careers.microsoft.com/us/en    ",
  },
  { id: 351, Title: "Microsoft", Link: "https://careers.microsoft.com/us/en" },
  {
    id: 352,
    Title: "Mind It Systems",
    Link: "https://www.minditsystems.com/careers/",
  },
  { id: 353, Title: "MindStrong", Link: "https://mindstrong.com/careers/" },
  { id: 354, Title: "MindTickle", Link: "https://www.mindtickle.com/careers/" },
  { id: 355, Title: "MindTickle", Link: "https://www.mindtickle.com/careers/" },
  { id: 356, Title: "Mindtree", Link: "https://www.mindtree.com/careers" },
  { id: 357, Title: "MobiKwik", Link: "https://mobikwik.recruiterbox.com/" },
  { id: 358, Title: "Mobikwik", Link: "https://www.mobikwik.com/career" },
  { id: 359, Title: "Monkhub", Link: "https://www.monkhub.com/jobs/" },
  {
    id: 360,
    Title: "Morgan Stanley",
    Link: "https://www.morganstanley.com/articles/morgan-stanley-india-careers",
  },
  {
    id: 361,
    Title: "Morgan Stanley",
    Link: "https://www.morganstanley.com/people-opportunities/",
  },
  { id: 362, Title: "Mount talent", Link: "https://careers.mounttalent.com/" },
  { id: 363, Title: "Mphasis", Link: "https://careers.mphasis.com/" },
  {
    id: 364,
    Title: "MPL",
    Link: "https://mpl.darwinbox.in/ms/candidate/careers",
  },
  { id: 365, Title: "Mquotient", Link: "http://www.mquotient.net/careers/" },
  {
    id: 366,
    Title: "Msys Technologies",
    Link: "https://www.msystechnologies.com/company/msys-careers/",
  },
  {
    id: 367,
    Title: "MultiGraphics Group",
    Link: "https://multigraphics.in/career",
  },
  { id: 368, Title: "Myntra", Link: "https://careers.myntra.com/" },
  { id: 369, Title: "Myntra", Link: "https://careers.myntra.com/" },
  { id: 370, Title: "Nagarro", Link: "https://www.nagarro.com/en/careers" },
  { id: 371, Title: "Nagarro", Link: "https://www.nagarro.com/en/careers" },
  { id: 372, Title: "NASDAQ", Link: "https://www.nasdaq.com/about/careers" },
  { id: 373, Title: "NASSCOM", Link: "https://nasscom.in/about-us/career" },
  {
    id: 374,
    Title: "National instruments",
    Link: "https://www.ni.com/en-in/about-ni/careers.html",
  },
  {
    id: 375,
    Title: "NatWest Group",
    Link: "https://jobs.natwestgroup.com/search/jobs/in/country/india",
  },
  {
    id: 376,
    Title: "navi",
    Link: "https://www.navifinserv.com/life-at-chaitanya",
  },
  { id: 377, Title: "NCR Corporation", Link: "https://www.ncr.com/careers" },
  {
    id: 378,
    Title: "NEC",
    Link: "https://in.nec.com/en_IN/career/jobs-at-NEC.html",
  },
  { id: 379, Title: "Neosoft", Link: "https://www.neosofttech.com/careers" },
  { id: 380, Title: "Nestle", Link: "https://www.nestle.in/jobs" },
  {
    id: 381,
    Title: "Net Solutions",
    Link: "https://www.netsolutions.com/careers/",
  },
  { id: 382, Title: "NetApp", Link: "https://www.arista.com/en/careers/india" },
  {
    id: 383,
    Title: "NetApp",
    Link: "https://www.netapp.com/company/careers/  ",
  },
  { id: 384, Title: "Netcracker", Link: "https://www.netcracker.com/careers/" },
  {
    id: 385,
    Title: "netflix",
    Link: "https://jobs.netflix.com/location?slug=mumbai-india",
  },
  { id: 386, Title: "Netguru", Link: "https://www.netguru.com/career" },
  {
    id: 387,
    Title: "Netmeds",
    Link: "https://netmeds.darwinbox.in/ms/candidate/careers",
  },
  { id: 388, Title: "Nike", Link: "https://jobs.nike.com/" },
  { id: 389, Title: "Ninjacart", Link: "https://ninjacart.in/careers" },
  { id: 390, Title: "Ninjacart", Link: "https://ninjacart.in/careers/" },
  { id: 391, Title: "Nokia", Link: "https://www.nokia.com/about-us/careers/" },
  {
    id: 392,
    Title: "NortonLifeLock",
    Link: "https://stage-www.nortonlifelock.com/us/en/careers/",
  },
  {
    id: 393,
    Title: "NTT Data Corporation",
    Link: "https://careers-inc.nttdata.com",
  },
  { id: 394, Title: "Nuro", Link: "https://www.nuro.ai/careers" },
  { id: 395, Title: "nurture.farm", Link: "https://nurture.farm/join-us/" },
  {
    id: 396,
    Title: "Nutanix",
    Link: "https://www.nutanix.com/company/careers",
  },
  {
    id: 397,
    Title: "Nutanix",
    Link: "https://www.nutanix.com/company/careers",
  },
  {
    id: 398,
    Title: "Nvidia",
    Link: "https://www.nvidia.com/en-in/about-nvidia/careers/",
  },
  {
    id: 399,
    Title: "NVIDIA",
    Link: "https://www.nvidia.com/en-in/about-nvidia/careers/",
  },
  { id: 400, Title: "Nykaa", Link: "https://www.nykaa.com/careers" },
  { id: 401, Title: "O9Solutions", Link: "https://o9solutions.com/careers/" },
  {
    id: 402,
    Title: "Observe.ai",
    Link: "https://www.observe.ai/careers#section-current-openings",
  },
  { id: 403, Title: "Obvious", Link: "https://obvious.in/careers" },
  { id: 404, Title: "Ocrolus", Link: "https://www.ocrolus.com/careers/" },
  { id: 405, Title: "Ola", Link: "https://ola.recruitee.com/" },
  { id: 406, Title: "Ola", Link: "https://www.olacabs.com/careers" },
  { id: 407, Title: "Olx", Link: "https://careers.olxgroup.com/" },
  { id: 408, Title: "Ongil", Link: "https://ongil.io/careers" },
  { id: 409, Title: "Optum", Link: "https://www.optum.in/about/careers.html" },
  {
    id: 410,
    Title: "Opus Consulting",
    Link: "https://www.opusconsulting.com/careers/",
  },
  {
    id: 411,
    Title: "Oracle",
    Link: "https://www.oracle.com/apac/corporate/careers/",
  },
  {
    id: 412,
    Title: "Oracle",
    Link: "https://www.oracle.com/in/corporate/careers/",
  },
  {
    id: 413,
    Title: "OYO",
    Link: "https://www.naukri.com/oyo-jobs-careers-2884032",
  },
  { id: 414, Title: "OYO", Link: "https://www.oyorooms.com/careers/" },
  {
    id: 415,
    Title: "Palo Alto Networks",
    Link: "https://jobs.paloaltonetworks.com/",
  },
  {
    id: 416,
    Title: "Palo Alto Networks",
    Link: "https://jobs.paloaltonetworks.com/en/",
  },
  { id: 417, Title: "Paramount", Link: "http://www.psinc3.com/jobs.html" },
  { id: 418, Title: "Park+", Link: "https://parkplus.io/we-are-hiring#hiring" },
  {
    id: 419,
    Title: "Paypal",
    Link: "https://www.paypal.com/us/webapps/mpp/jobs/students-and-grads/internships",
  },
  {
    id: 420,
    Title: "PayScale",
    Link: "https://www.payscale.com/research/IN/Job",
  },
  { id: 421, Title: "Paytm", Link: "https://paytm.com/careers/" },
  { id: 422, Title: "PayU", Link: "https://payu.in/careers" },
  { id: 423, Title: "Pegasystems", Link: "https://www.pega.com/about/careers" },
  {
    id: 424,
    Title: "PeopleStrong",
    Link: "https://www.peoplestrong.com/careers/",
  },
  { id: 425, Title: "Persistent", Link: "https://www.persistent.com/careers/" },
  { id: 426, Title: "PharmEasy", Link: "https://pharmeasy.in/careers/" },
  {
    id: 427,
    Title: "Philips",
    Link: "https://www.careers.philips.com/global/en",
  },
  { id: 428, Title: "Phonepe", Link: "https://www.phonepe.com/careers/" },
  { id: 429, Title: "PixelCrayons", Link: "https://www.pixelcrayons.com/" },
  {
    id: 430,
    Title: "PlanView India",
    Link: "https://www.planview.com/company/careers/",
  },
  { id: 431, Title: "Playment", Link: "https://www.playment.io/careers" },
  { id: 432, Title: "Plintron", Link: "https://www.plintron.com/en/career" },
  {
    id: 433,
    Title: "Postman",
    Link: "https://www.postman.com/company/careers/",
  },
  { id: 434, Title: "Practo", Link: "https://practo.app.param.ai/jobs" },
  { id: 435, Title: "Practo", Link: "https://practo.app.param.ai/jobs/" },
  { id: 436, Title: "Priceline", Link: "https://careers.priceline.com/search" },
  {
    id: 437,
    Title: "Principal",
    Link: "https://www.principal.com/about-us/careers/global-jobs",
  },
  { id: 438, Title: "Privado.ai", Link: "https://www.privado.ai" },
  { id: 439, Title: "Procore", Link: "https://www.procore.com/jobs" },
  { id: 440, Title: "Prodapt", Link: "https://www.prodapt.com/en/careers/" },
  { id: 441, Title: "Proptiger", Link: "https://www.proptiger.com/careers" },
  {
    id: 442,
    Title: "Protegrity",
    Link: "https://jobs.lever.co/protegrity?location=Bengaluru",
  },
  {
    id: 443,
    Title: "Providence Healthcare",
    Link: "https://www.providencehealthcare.org/careers",
  },
  {
    id: 444,
    Title: "Proximity Labs",
    Link: "https://www.proximity.tech/careers",
  },
  {
    id: 445,
    Title: "Publicis Sapient",
    Link: "https://careers.publicissapient.com/",
  },
  { id: 446, Title: "PubMatic", Link: "https://pubmatic.com/careers/home/" },
  { id: 447, Title: "QBurst", Link: "https://www.qburst.com/company/career/" },
  {
    id: 448,
    Title: "Qualcomm",
    Link: "https://www.qualcomm.com/company/careers",
  },
  { id: 449, Title: "Quikr", Link: "https://www.quikr.com/html/jobs.php" },
  { id: 450, Title: "Quora", Link: "https://www.quora.com/careers" },
  { id: 451, Title: "RadixWeb", Link: "https://radixweb.com/current-openings" },
  { id: 452, Title: "Rakuten", Link: "https://rakuten.careers/" },
  { id: 453, Title: "Razorpay", Link: "https://razorpay.com/jobs/" },
  { id: 454, Title: "RedHat", Link: "https://www.redhat.com/en/jobs" },
  { id: 455, Title: "Reelo", Link: "https://angel.co/company/reelohq" },
  {
    id: 456,
    Title: "Refinery29",
    Link: "https://corporate.r29.com/careers#careers-jobs",
  },
  { id: 457, Title: "Reliance", Link: "https://careers.ril.com/" },
  { id: 458, Title: "Revalsys", Link: "https://www.revalsys.com/careers.html" },
  { id: 459, Title: "Rippling", Link: "https://www.rippling.com/careers" },
  { id: 460, Title: "Rivigo", Link: "https://www.rivigo.com/careers/" },
  {
    id: 461,
    Title: "Rocket Companies",
    Link: "https://www.myrocketcareer.com/",
  },
  {
    id: 462,
    Title: "Rockstar Games",
    Link: "https://www.rockstargames.com/careers/",
  },
  { id: 463, Title: "Rubrik", Link: "https://www.rubrik.com/company/careers" },
  { id: 464, Title: "Rupeek", Link: "https://www.rivigo.com/careers/" },
  { id: 465, Title: "S&P Global", Link: "https://careers.spglobal.com/jobs" },
  { id: 466, Title: "Saavan", Link: "https://www.jiosaavn.com/corporate/jobs" },
  {
    id: 467,
    Title: "Sabre corporation",
    Link: "https://www.sabre.com/careers/",
  },
  {
    id: 468,
    Title: "Salesforce",
    Link: "https://www.salesforce.com/company/careers/",
  },
  {
    id: 469,
    Title: "Samsung",
    Link: "https://www.samsung.com/in/about-us/careers/",
  },
  { id: 470, Title: "SAP", Link: "https://jobs.sap.com/" },
  {
    id: 471,
    Title: "Sapphire Solutions",
    Link: "https://www.sapphiresolutions.net/careers",
  },
  { id: 472, Title: "Scality", Link: "https://www.scality.com/careers" },
  { id: 473, Title: "Seamless.Ai", Link: "https://www.seamless.ai/careers" },
  {
    id: 474,
    Title: "Secure Logic",
    Link: "https://securelogicgroup.com/about-us/careers/",
  },
  {
    id: 475,
    Title: "Seimens",
    Link: "https://new.siemens.com/global/en/company/jobs.html",
  },
  { id: 476, Title: "SendinBlue", Link: "https://jobs.sendinblue.com/en" },
  { id: 477, Title: "SerpApi", Link: "https://serpapi.com/team" },
  {
    id: 478,
    Title: "ServiceNow",
    Link: "https://www.servicenow.com/careers.html",
  },
  {
    id: 479,
    Title: "Servicenow",
    Link: "https://www.servicenow.com/careers.html",
  },
  { id: 480, Title: "Shaadi.com", Link: "https://careers.shaadi.com/" },
  { id: 481, Title: "ShareChat", Link: "https://sharechat.com/careers" },
  { id: 482, Title: "Shell", Link: "https://www.shell.com/careers.html" },
  { id: 483, Title: "Shipsy", Link: "https://shipsy.io/career/" },
  { id: 484, Title: "Shopee", Link: "https://careers.shopee.sg/" },
  { id: 485, Title: "Sidebench", Link: "https://sidebench.com/careers/" },
  {
    id: 486,
    Title: "Siemens Healthineers",
    Link: "https://www.siemens-healthineers.com/en-in/careers",
  },
  {
    id: 487,
    Title: "Siemens",
    Link: "https://new.siemens.com/global/en/company/jobs/search-careers.html",
  },
  { id: 488, Title: "Sigmoid", Link: "https://www.sigmoid.com/careers/" },
  { id: 489, Title: "Simform", Link: "https://www.simform.com/careers/" },
  { id: 490, Title: "Simreka", Link: "https://simreka.com/work-with-us/" },
  {
    id: 491,
    Title: "SIRI Innovations",
    Link: "https://www.siriinnovations.com/careers",
  },
  {
    id: 492,
    Title: "Sirion Labs",
    Link: "https://www.sirionlabs.com/careers/",
  },
  {
    id: 493,
    Title: "SkillVertex",
    Link: "https://www.linkedin.com/jobs/search/?f_C=75860188&geoId=92000000",
  },
  {
    id: 494,
    Title: "Skyleaf Consultants",
    Link: "https://www.naukri.com/skyleaf-consultants-jobs-careers-913356",
  },
  { id: 495, Title: "Skyroot Aerospace", Link: "https://skyroot.in/join/" },
  { id: 496, Title: "Slack", Link: "https://slack.com/intl/en-in/careers" },
  { id: 497, Title: "Slice", Link: "https://www.slice.is/work-at-slice/" },
  {
    id: 498,
    Title: "Sling Media",
    Link: "https://www.linkedin.com/jobs/sling-media-jobs/?originalSubdomain=in",
  },
  {
    id: 499,
    Title: "Smith Detection",
    Link: "https://www.smithsdetection.com/careers/",
  },
  { id: 500, Title: "Snapdeal", Link: "https://qa.snapdeal.com/info/jobs" },
  { id: 501, Title: "Snowflake", Link: "https://careers.snowflake.com" },
  {
    id: 502,
    Title: "Solusoft",
    Link: "https://www.solu-soft.com/careers_workinghere.html",
  },
  {
    id: 503,
    Title: "Sopra Steria",
    Link: "https://www.soprasteria.com/careers",
  },
  { id: 504, Title: "Spec India", Link: "https://www.spec-india.com/career" },
  { id: 505, Title: "Spectrum", Link: "https://jobs.spectrum.com/" },
  { id: 506, Title: "Spinny", Link: "https://spinny.freshteam.com/jobs" },
  { id: 507, Title: "Spotify", Link: "https://www.spotifyjobs.com/" },
  { id: 508, Title: "Sprinklr", Link: "https://www.sprinklr.com/careers" },
  { id: 509, Title: "SquadStack", Link: "https://www.squadstack.com/careers/" },
  { id: 510, Title: "Square", Link: "https://careers.squareup.com/us/en" },
  { id: 511, Title: "Stripe", Link: "https://stripe.com/in/jobs" },
  {
    id: 512,
    Title: "SumoLogic",
    Link: "https://www.sumologic.com/company/careers/",
  },
  { id: 513, Title: "SunGard", Link: "https://careers.sungardas.com" },
  {
    id: 514,
    Title: "Sunrise JOb",
    Link: "http://www.sunrisejobconsultancy.com",
  },
  {
    id: 515,
    Title: "Sunsure Energy",
    Link: "https://www.sunsure-energy.com/careers",
  },
  { id: 516, Title: "Swiggy", Link: "https://careers.swiggy.com/" },
  {
    id: 517,
    Title: "Syberry",
    Link: "https://www.syberry.com/company/our-team",
  },
  {
    id: 518,
    Title: "Symantec Software Company",
    Link: "https://www.careerbliss.com/symantec/",
  },
  {
    id: 519,
    Title: "Symphoni HR Private Limited",
    Link: "https://symphonihr.com",
  },
  { id: 520, Title: "Synopsys", Link: "https://www.synopsys.com/careers.html" },
  { id: 521, Title: "Syntel", Link: "https://www.atos-syntel.net/careers" },
  { id: 522, Title: "Syska", Link: "https://syska.co.in/career" },
  {
    id: 523,
    Title: "T Systems",
    Link: "https://www.t-systems.com/in/en/careers",
  },
  {
    id: 524,
    Title: "Talent HR Networks",
    Link: "https://www.naukri.com/talent-hr-networks-pvt-ltd-jobs-careers-543887",
  },
  { id: 525, Title: "Target", Link: "https://corporate.target.com/careers" },
  { id: 526, Title: "TaskBob", Link: "https://taskbob2015.recruiterbox.com/" },
  {
    id: 527,
    Title: "TATA Advanced Sysytems Ltd",
    Link: "https://www.tataadvancedsystems.com/careers.php",
  },
  { id: 528, Title: "TatvaSoft", Link: "https://www.tatvasoft.com/career" },
  {
    id: 529,
    Title: "TCS",
    Link: "https://www.tcs.com/careers?country=IN&lang=EN",
  },
  { id: 530, Title: "TE Connectivity", Link: "https://careers.te.com/" },
  {
    id: 531,
    Title: "TEK Systems",
    Link: "https://www.teksystems.com/en-in/careers",
  },
  { id: 532, Title: "Tekion", Link: "https://tekion.com/careers" },
  {
    id: 533,
    Title: "Tencent Holdings Ltd",
    Link: "https://www.tencent.com/en-us/about.html",
  },
  { id: 534, Title: "Teradata", Link: "https://careers.teradata.com/" },
  { id: 535, Title: "Tesla", Link: "https://www.tesla.com/about" },
  { id: 536, Title: "texas instruments", Link: "https://careers.ti.com/" },
  { id: 537, Title: "Texas Instruments", Link: "https://careers.ti.com/" },
  {
    id: 538,
    Title: "ThoughtSpot",
    Link: "https://www.thoughtspot.com/careers-listing",
  },
  {
    id: 539,
    Title: "ThoughtWorks",
    Link: "https://www.thoughtworks.com/careers/jobs",
  },
  {
    id: 540,
    Title: "Times Internet",
    Link: "https://timesinternet.in/careers",
  },
  {
    id: 541,
    Title: "Topcoder",
    Link: "https://www.topcoder.com/company/jobs/",
  },
  { id: 542, Title: "Toppr", Link: "https://www.toppr.com/jobs/" },
  { id: 543, Title: "Toptal", Link: "https://www.toptal.com/careers" },
  {
    id: 544,
    Title: "Tower Research",
    Link: "https://www.tower-research.com/positions",
  },
  {
    id: 545,
    Title: "Treebo Hotels",
    Link: "https://www.linkedin.com/company/treebohotels/jobs/",
  },
  {
    id: 546,
    Title: "Trella Health",
    Link: "https://www.trellahealth.com/careers/",
  },
  {
    id: 547,
    Title: "Trigent Software",
    Link: "https://www.trigent.com/company/careers/",
  },
  {
    id: 548,
    Title: "Trigyn",
    Link: "https://www.trigyn.com/job/etl-developer-data-engineer",
  },
  { id: 549, Title: "Turvo", Link: "https://turvo.com/careers/" },
  { id: 550, Title: "Twilio", Link: "https://www.twilio.com/company/jobs" },
  { id: 551, Title: "Twitter", Link: "https://careers.twitter.com/" },
  { id: 552, Title: "Uber", Link: "https://www.uber.com/us/en/careers/" },
  {
    id: 553,
    Title: "Ubique Systems",
    Link: "https://www.ubique-systems.com/ubq-current-opening.php",
  },
  {
    id: 554,
    Title: "Ubisoft",
    Link: "https://www.ubisoft.com/en-us/company/careers",
  },
  { id: 555, Title: "Udaan", Link: "https://careers.udaan.com/" },
  { id: 556, Title: "Ultimate software", Link: "https://www.ukg.com/careers" },
  { id: 557, Title: "Unacadamy", Link: "https://unacademy.com/careers" },
  { id: 558, Title: "Unicommerce", Link: "https://unicommerce.com/careers/" },
  { id: 559, Title: "Unisys", Link: "https://jobs.unisys.com/us/en" },
  { id: 560, Title: "Unite Us", Link: "https://uniteus.com/our-careers/" },
  { id: 561, Title: "Upgrad", Link: "https://www.upgrad.com/us/careers/" },
  { id: 562, Title: "Uplers", Link: "https://www.uplers.com/careers/" },
  { id: 563, Title: "Upstox", Link: "https://jobs.lever.co/upstox  " },
  {
    id: 564,
    Title: "Urban company",
    Link: "https://careers.urbancompany.com/ ",
  },
  {
    id: 565,
    Title: "Urban Ladder",
    Link: "https://www.urbanladder.com/careers#undefined",
  },
  { id: 566, Title: "V2soft", Link: "https://www.v2soft.com/careers" },
  { id: 567, Title: "ValueLabs", Link: "https://www.valuelabs.com/careers/" },
  {
    id: 568,
    Title: "Vehant Technologies",
    Link: "https://www.vehant.com/current-openings",
  },
  {
    id: 569,
    Title: "Velotio Technologies",
    Link: "https://www.velotio.com/careers",
  },
  { id: 570, Title: "Viasat", Link: "https://careers.viasat.com/" },
  { id: 571, Title: "Vicara", Link: "https://vicara.ch/careers/" },
  { id: 572, Title: "Visa", Link: "https://www.visa.co.in/careers.html" },
  { id: 573, Title: "VMware", Link: "https://careers.vmware.com/main/" },
  { id: 574, Title: "Vogo", Link: "https://vogo.in/careers/" },
  { id: 575, Title: "Vokal", Link: "https://www.vokal.io/careers" },
  { id: 576, Title: "Vsoft", Link: "https://www.vfirst.com/join-the-joy" },
  { id: 577, Title: "Walmart", Link: "https://careers.walmart.com/" },
  {
    id: 578,
    Title: "Warner Bros.",
    Link: "https://warnermediacareers.com/warner-bros-jobs",
  },
  { id: 579, Title: "Waymo", Link: "https://waymo.com/careers/" },
  {
    id: 580,
    Title: "Wells Fargo",
    Link: "https://www.wellsfargo.com/about/careers/",
  },
  {
    id: 581,
    Title: "Wells Fargo",
    Link: "https://www.wellsfargo.com/about/careers/",
  },
  {
    id: 582,
    Title: "Western Digital",
    Link: "https://jobs.westerndigital.com/",
  },
  { id: 583, Title: "Whatfix", Link: "https://whatfix.com/careers/" },
  { id: 584, Title: "Wipro", Link: "https://careers.wipro.com/careers-home/" },
  { id: 585, Title: "Wissda Consulting", Link: "http://www.wissda.com" },
  { id: 586, Title: "Wooqer", Link: "https://wooqer.com/careers/" },
  {
    id: 587,
    Title: "World Wide Technology",
    Link: "https://www.wwt.com/about/careers",
  },
  { id: 588, Title: "WorldQuant", Link: "https://www.worldquant.com/careers/" },
  { id: 589, Title: "Xero", Link: "https://www.xero.com/about/careers/" },
  { id: 590, Title: "Xiaomi", Link: "https://xiaomi.app.param.ai/jobs/" },
  {
    id: 591,
    Title: "Xicom Technologies",
    Link: "https://www.xicom.biz/careers/",
  },
  { id: 592, Title: "Xilinx", Link: "https://careers.xilinx.com/" },
  {
    id: 593,
    Title: "Xoriant",
    Link: "https://www.xoriant.com/about-xoriant/careers",
  },
  { id: 594, Title: "Yahoo", Link: "https://research.yahoo.com/careers" },
  { id: 595, Title: "Yellow.ai", Link: "https://yellow.ai/career" },
  { id: 596, Title: "Yelp", Link: "https://www.yelp.careers/us/en" },
  { id: 597, Title: "Yobisys", Link: "https://www.yobisys.com/career.htm" },
  { id: 598, Title: "Yugabyte", Link: "https://www.yugabyte.com/careers/" },
  { id: 599, Title: "Yulu Bikes", Link: "https://www.yulu.bike/careers/" },
  {id:600,Title: 'Zenmonics Software', Link: 'https://www.naukri.com/zenmonics-software-pvt-ltd-jobs-careers-644929'},
{id:601,Title: 'Zensar Technologies', Link: 'https://zensar.com/careers'},
{id:602,Title: 'Zerodha', Link: 'https://careers.zerodha.com/'},
{id:603,Title: 'Zeta', Link: 'https://careers.zeta.tech/work-with-us/'},
{id:604,Title: 'ZivaMe', Link: 'https://careers.zivame.com/'},
{id:605,Title: 'Zoho', Link: 'https://careers.zohocorp.com/jobs/Careers'},
{id:606,Title: 'Zomato', Link: 'https://www.zomato.com/careers'},
{id:607,Title: 'Zoom', Link: 'https://zoom.wd5.myworkdayjobs.com/Zoom'},
{id:608,Title: 'ZoomCar', Link: 'https://www.zoomcar.com/careers'},
{id:609,Title: 'ZS', Link: 'https://jobs.zs.com/all/jobs'},
{id:610,Title: 'Zynga', Link: 'https://www.zynga.com/jobs/careers/'},
{id:611,Title: 'Pinterest', Link: 'https://www.pinterestcareers.com/'},
];


export default careerData;